spring.datasource.url=jdbc:h2:mem:pixservice;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Usaremos scripts @Sql (setup.sql + datasets) para criar/popular o schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false

logging.level.root=WARN
logging.level.com.example.pixservice=DEBUG